### ISSUE TITLE
'from plotstyle import plot_style' stört fig.add_subplot(projection='polar')

### ISSUE THREAD

**Issue by saschuta** [bendalab/plottools#4]
Der import von 'from plotstyle import plot_style'  führt dazu, dass 'ax_pol = fig.add_subplot(projection='polar')' nicht funktioniert. 
Der Fehler ist :
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\alexi\AppData\Roaming\Python\Python39\site-packages\matplotlib\figure.py", line 772, in add_subplot
    ax = subplot_class_factory(projection_class)(self, *args, **pkw)
  File "C:\Users\alexi\AppData\Roaming\Python\Python39\site-packages\matplotlib\axes\_subplots.py", line 34, in __init__
    self._axes_class.__init__(self, fig, [0, 0, 1, 1], **kwargs)
  File "C:\Users\alexi\AppData\Roaming\Python\Python39\site-packages\matplotlib\projections\polar.py", line 777, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\alexi\Desktop\work\code\plottools\spines.py", line 730, in __axes_init_spines__
    ax.show_spines(mpl.rcParams['axes.spines.show'])
  File "C:\Users\alexi\Desktop\work\code\plottools\spines.py", line 130, in show_spines
    ax.spines['top'].set_visible('top' in xspines)
  File "C:\Users\alexi\AppData\Roaming\Python\Python39\site-packages\matplotlib\spines.py", line 572, in __getitem__
    return self._dict[key]
KeyError: 'top'

**Comment by janscience** [comment]
Fixed!
